# Files pulled in by include!/include_bytes!/include_str! that the
# default source globs miss.
extra_srcs = [
    "tests/data/char16trie/empty.toml",
    "tests/data/char16trie/months.toml",
    "tests/data/char16trie/test_a.toml",
    "tests/data/char16trie/test_a_ab.toml",
    "tests/data/char16trie/test_branches.toml",
    "tests/data/char16trie/test_compact.toml",
    "tests/data/char16trie/test_long_branch.toml",
    "tests/data/char16trie/test_long_sequence.toml",
    "tests/data/char16trie/test_shortest_branch.toml",
    "tests/data/cpt/free-blocks.16.toml",
    "tests/data/cpt/free-blocks.32.toml",
    "tests/data/cpt/free-blocks.8.toml",
    "tests/data/cpt/free-blocks.small16.toml",
    "tests/data/cpt/grow-data.16.toml",
    "tests/data/cpt/grow-data.32.toml",
    "tests/data/cpt/grow-data.8.toml",
    "tests/data/cpt/grow-data.small16.toml",
    "tests/data/cpt/planes.toml",
    "tests/data/cpt/set-empty.16.toml",
    "tests/data/cpt/set-empty.32.toml",
    "tests/data/cpt/set-empty.8.toml",
    "tests/data/cpt/set-empty.small16.toml",
    "tests/data/cpt/set-single-value.16.toml",
    "tests/data/cpt/set-single-value.32.toml",
    "tests/data/cpt/set-single-value.8.toml",
    "tests/data/cpt/set-single-value.small16.toml",
    "tests/data/cpt/set1.16.toml",
    "tests/data/cpt/set1.32.toml",
    "tests/data/cpt/set1.8.toml",
    "tests/data/cpt/set1.small16.toml",
    "tests/data/cpt/set2-overlap.16.toml",
    "tests/data/cpt/set2-overlap.32.toml",
    "tests/data/cpt/set2-overlap.small16.toml",
    "tests/data/cpt/set3-initial-9.16.toml",
    "tests/data/cpt/set3-initial-9.32.toml",
    "tests/data/cpt/set3-initial-9.8.toml",
    "tests/data/cpt/set3-initial-9.small16.toml",
    "tests/data/cpt/short-all-same.16.toml",
    "tests/data/cpt/short-all-same.8.toml",
    "tests/data/cpt/short-all-same.small16.toml",
    "tests/data/cpt/small0-in-fast.16.toml",
    "tests/data/cpt/small0-in-fast.32.toml",
    "tests/data/cpt/small0-in-fast.8.toml",
    "tests/data/cpt/small0-in-fast.small16.toml",
]
