name = "vidya"
version = "0.1.0"
gleam = ">= 1.13.0"
licences = ["MIT"]
description = "Declarative Vidya UI builders — design egui apps in Gleam"
repository = { type = "github", user = "codegod100", repo = "vidya" }
target = "javascript"
links = [
  { title = "Vidya", href = "https://tangled.org/nandi.uk/vidya" },
  { title = "Gleam", href = "https://gleam.run" },
]

[dependencies]
gleam_stdlib = ">= 0.60.0 and < 2.0.0"
gleam_json = ">= 3.0.0 and < 4.0.0"

[dev-dependencies]
gleeunit = ">= 1.2.0 and < 2.0.0"
